spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/bslota/config-repository'
          clone-on-start: true

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance

# Server properties
server:
  port: 8888
