eureka:
  client:
    service-url:
      default-zone: http://discovery-server:8761/eureka/

spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: "kafka:2181"
          brokers: "kafka:9092"